set term ^ ;
EXECUTE BLOCK AS BEGIN
INSERT INTO C000133 VALUES ('01', 'Operação Tributável com Alíquota Básica');
INSERT INTO C000133 VALUES   ('02', 'Operação Tributável com Alíquota Diferenciada');
INSERT INTO C000133 VALUES    ('03', 'Operação Tributável com Alíquota por Unidade de Medida de Produto');
INSERT INTO C000133 VALUES    ('04', 'Operação Tributável Monofásica – Revenda a Alíquota Zero');
INSERT INTO C000133 VALUES    ('05', 'Operação Tributável por Substituição Tributária');
INSERT INTO C000133 VALUES    ('06', 'Operação Tributável a Alíquota Zero');
INSERT INTO C000133 VALUES    ('07', 'Operação Isenta da Contribuição');
INSERT INTO C000133 VALUES    ('08', 'Operação sem Incidência da Contribuição');
INSERT INTO C000133 VALUES    ('09', 'Operação com Suspensão da Contribuição');
INSERT INTO C000133 VALUES    ('49', 'Outras Operações de Saída');
INSERT INTO C000133 VALUES    ('50', 'Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO C000133 VALUES    ('51', 'Operação com Direito a Crédito – Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno');
INSERT INTO C000133 VALUES    ('52', 'Operação com Direito a Crédito – Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO C000133 VALUES    ('53', 'Operação com Direito a Crédito – Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO C000133 VALUES    ('54', 'Operação com Direito a Crédito – Vinculada a Receitas Tributadas no Mercado Interno e de Exportação');
INSERT INTO C000133 VALUES    ('55', 'Operação com Direito a Crédito – Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO C000133 VALUES   ('56', 'Operação com Direito a Crédito – Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação');
INSERT INTO C000133 VALUES    ('60', 'Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita Tributada no Mercado Interno');
INSERT INTO C000133 VALUES    ('61', 'Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita Não Tributada no Mercado Interno');
INSERT INTO C000133 VALUES   ('62', 'Crédito Presumido – Operação de Aquisição Vinculada Exclusivamente a Receita de Exportação');
INSERT INTO C000133 VALUES   ('63', 'Crédito Presumido – Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno');
INSERT INTO C000133 VALUES   ('64', 'Crédito Presumido – Operação de Aquisição Vinculada a Receitas Tributadas no Mercado Interno e de Exportação');
INSERT INTO C000133 VALUES  ('65', 'Crédito Presumido – Operação de Aquisição Vinculada a Receitas Não-Tributadas no Mercado Interno e de Exportação');
INSERT INTO C000133 VALUES   ('66', 'Crédito Presumido – Operação de Aquisição Vinculada a Receitas Tributadas e Não-Tributadas no Mercado Interno, e de Exportação');
INSERT INTO C000133 VALUES   ('67', 'Crédito Presumido – Outras Operações');
INSERT INTO C000133 VALUES   ('70', 'Operação de Aquisição sem Direito a Crédito');
INSERT INTO C000133 VALUES  ('71', 'Operação de Aquisição com Isenção');
INSERT INTO C000133 VALUES  ('72', 'Operação de Aquisição com Suspensão');
INSERT INTO C000133 VALUES   ('73', 'Operação de Aquisição a Alíquota Zero');
INSERT INTO C000133 VALUES   ('74', 'Operação de Aquisição sem Incidência da Contribuição');
INSERT INTO C000133 VALUES   ('75', 'Operação de Aquisição por Substituição Tributária');
INSERT INTO C000133 VALUES   ('98', 'Outras Operações de Entrada');
INSERT INTO C000133 VALUES   ('99', 'Outras Operações');
END^
